=== wmo-im/wis2-notification-message/schemas/wis2-notification-message-bundled.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.wmo.int/wnm/1.1.0/schemas/wis2-notification-message-bundled.json",
  "title": "WIS2 Notification Message Encoding",
  "description": "WIS2 Notification Message Encoding",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "UUID (RFC4122) - Guarantee uniqueness of the message over (at least) a 24h period."
    },
    "conformsTo": {
      "type": "array",
      "contains": {
        "const": "http://wis.wmo.int/spec/wnm/1/conf/core"
      }
    },
    "version": {
      "type": "string",
      "description": "DEPRECATED, please use `conformsTo`.",
      "const": "v04"
    },
    "type": {
      "type": "string",
      "enum": [
        "Feature"
      ]
    },
    "geometry": {
      "oneOf": [
        {
          "enum": [
            null
          ]
        },
        {
          "type": "object",
          "required": [
            "type",
            "coordinates"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "Point"
              ]
            },
            "coordinates": {
              "type": "array",
              "minItems": 2,
              "items": {
                "type": "number"
              }
            }
          }
        },
        {
          "type": "object",
          "required": [
            "type",
            "coordinates"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "Polygon"
              ]
            },
            "coordinates": {
              "type": "array",
              "items": {
                "type": "array",
                "minItems": 4,
                "items": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      ]
    },
    "properties": {
      "type": "object",
      "properties": {
        "pubtime": {
          "type": "string",
          "format": "date-time",
          "description": "Identifies the date/time of when the file was posted/published, in RFC3339 format.\nThe publication date/time is critical for subscribers to prevent message loss by knowing\ntheir lag (how far behind the publisher they are).\n"
        },
        "data_id": {
          "type": "string",
          "description": "Unique identifier of the data as defined by the data producer.\nData producers SHOULD NOT use an opaque id, but something meaningful to support client side filtering.\n"
        },
        "metadata_id": {
          "type": "string",
          "description": "Identifier for associated discovery metadata record to which the notification applies to.\nThe identification SHOULD be from a WCMP2 discovery metadata record identifier from the WIS2\nGlobal Discovery Catalogue. Identifiers based on external catalogue systems MAY be articulated as additional links.\n"
        },
        "producer": {
          "type": "string",
          "description": "Identifies the provider that initially captured and processed the source data, in support of data distribution on behalf of other Members.\n"
        },
        "global-cache": {
          "type": "string",
          "description": "Centre identifier of Global Cache Service producing the notification.\n"
        },
        "datetime": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time",
          "description": "Identifies the date/time of the data being published, in RFC3339 format."
        },
        "start_datetime": {
          "type": "string",
          "format": "date-time",
          "description": "Identifies the start date/time date of the data being published, in RFC3339 format."
        },
        "end_datetime": {
          "type": "string",
          "format": "date-time",
          "description": "Identifies the end date/time date of the data being published, in RFC3339 format."
        },
        "cache": {
          "type": "boolean",
          "description": "Whether the data in the notification should be cached (if not specified, the default value is `true`).\nWhen set to `false`, WIS2 Global Cache services do not cache the canonical link, and publish the\nnotification with an unmodified canonical link (which points back to the endpoint as specified by the data producer).\nThe notification is always published by the Global Cache regardless to the `cache` topic.\n",
          "default": true
        },
        "integrity": {
          "type": "object",
          "description": "Specifies a checksum to be applied to the data to ensure that the download is accurate.",
          "properties": {
            "method": {
              "type": "string",
              "description": "A specific set of methods for calculating the checksum algorithms:\n* ``sha256``: the Secure Hash Algorithm 2, 256 bits, value is base64 encoded.\n* ``sha384``: the Secure Hash Algorithm 2, 384 bits, value is base64 encoded.\n* ``sha512``: the Secure Hash Algorithm 2, 512 bits, value is base64 encoded.\n* ``sha3-256``: the Secure Hash Algorithm 3, 256 bits, value is base64 encoded.\n* ``sha3-384``: the Secure Hash Algorithm 3, 384 bits, value is base64 encoded.\n* ``sha3-512``: the Secure Hash Algorithm 3, 512 bits, value is base64 encoded.\n",
              "enum": [
                "sha256",
                "sha384",
                "sha512",
                "sha3-256",
                "sha3-384",
                "sha3-512"
              ]
            },
            "value": {
              "type": "string",
              "contentEncoding": "base64",
              "description": "Checksum value."
            }
          },
          "required": [
            "method",
            "value"
          ]
        },
        "content": {
          "type": "object",
          "description": "Used to embed small products inline within the message.",
          "properties": {
            "encoding": {
              "type": "string",
              "description": "Encoding of content",
              "enum": [
                "utf-8",
                "base64",
                "gzip"
              ]
            },
            "size": {
              "type": "integer",
              "maximum": 4096,
              "description": "Number of bytes contained in the file. Together with the ``integrity`` property, it provides additional assurance that file content was accurately received.\nNote that the limit takes into account the data encoding used, including data compression (for example `gzip`).\n"
            },
            "value": {
              "type": "string",
              "description": "The inline content of the file.",
              "maxLength": 4096
            }
          },
          "required": [
            "encoding",
            "size",
            "value"
          ]
        }
      },
      "required": [
        "pubtime",
        "data_id",
        "metadata_id"
      ],
      "oneOf": [
        {
          "allOf": [
            {
              "required": [
                "start_datetime",
                "end_datetime"
              ]
            }
          ]
        },
        {
          "allOf": [
            {
              "required": [
                "datetime"
              ]
            }
          ]
        }
      ]
    },
    "links": {
      "type": "array",
      "minItems": 1,
      "items": {
        "allOf": [
          {
            "allOf": [
              {
                "type": "object",
                "required": [
                  "rel"
                ],
                "properties": {
                  "rel": {
                    "type": "string",
                    "description": "The type or semantics of the relation.",
                    "example": "alternate"
                  },
                  "type": {
                    "type": "string",
                    "description": "A hint indicating what the media type of the result of dereferencing the link should be.",
                    "example": "application/geo+json"
                  },
                  "hreflang": {
                    "type": "string",
                    "description": "A hint indicating what the language of the result of dereferencing the link should be.",
                    "example": "en"
                  },
                  "title": {
                    "type": "string",
                    "description": "Used to label the destination of a link such that it can be used as a human-readable identifier.",
                    "example": "Trierer Strasse 70, 53115 Bonn"
                  },
                  "length": {
                    "type": "integer"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "href"
                ],
                "properties": {
                  "href": {
                    "type": "string",
                    "description": "The URI of the link target.",
                    "example": "http://data.example.com/buildings/123"
                  }
                }
              }
            ]
          },
          {
            "properties": {
              "security": {
                "type": "object",
                "patternProperties": {
                  "^[a-zA-Z0-9\\.\\-_]+$": {
                    "oneOf": [
                      {
                        "$ref": "#/definitions/Schema_Reference"
                      },
                      {
                        "$ref": "#/definitions/Schema_SecurityScheme"
                      }
                    ]
                  }
                }
              }
            }
          }
        ]
      }
    }
  },
  "oneOf": [
    {
      "required": [
        "id",
        "conformsTo",
        "type",
        "geometry",
        "properties",
        "links"
      ]
    },
    {
      "required": [
        "id",
        "version",
        "type",
        "geometry",
        "properties",
        "links"
      ]
    }
  ],
  "example": {
    "id": "31e9d66a-cd83-4174-9429-b932f1abe1be",
    "version": "v04",
    "type": "Feature",
    "geometry": {
      "type": "Point",
      "coordinates": [
        6.146255135536194,
        46.223296618227444
      ]
    },
    "properties": {
      "pubtime": "2022-03-20T04:50:18.314854383Z",
      "datetime": "2022-03-20T04:45:00Z",
      "integrity": {
        "method": "sha512",
        "value": "A2KNxvks...S8qfSCw=="
      },
      "data_id": "dataset/123/data-granule/UANT01_CWAO_200445___15103.bufr4",
      "metadata_id": "urn:wmo:md:ca-eccc-msc:observations.swob",
      "content": {
        "encoding": "utf-8",
        "value": "encoded bytes from the file",
        "size": 457
      }
    },
    "links": [
      {
        "href": "https://example.org/data/4Pubsub/92c557ef-d28e-4713-91af-2e2e7be6f8ab.bufr4",
        "rel": "canonical",
        "type": "application/bufr"
      },
      {
        "href": "https://example.org/oapi/collections/my-dataset/items/my-data-granule",
        "rel": "item",
        "type": "application/json"
      }
    ]
  },
  "definitions": {
    "Schema_APIKeySecurityScheme": {
      "type": "object",
      "required": [
        "type",
        "name",
        "in"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "apiKey"
          ]
        },
        "name": {
          "type": "string"
        },
        "in": {
          "type": "string",
          "enum": [
            "header",
            "query",
            "cookie"
          ]
        },
        "description": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_AuthorizationCodeOAuthFlow": {
      "type": "object",
      "required": [
        "authorizationUrl",
        "tokenUrl"
      ],
      "properties": {
        "authorizationUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "tokenUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "refreshUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "scopes": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_ClientCredentialsFlow": {
      "type": "object",
      "required": [
        "tokenUrl"
      ],
      "properties": {
        "tokenUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "refreshUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "scopes": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_HTTPSecurityScheme": {
      "type": "object",
      "required": [
        "scheme",
        "type"
      ],
      "properties": {
        "scheme": {
          "type": "string"
        },
        "bearerFormat": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "http"
          ]
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false,
      "oneOf": [
        {
          "description": "Bearer",
          "properties": {
            "scheme": {
              "enum": [
                "bearer"
              ]
            }
          }
        },
        {
          "description": "Non Bearer",
          "not": {
            "required": [
              "bearerFormat"
            ]
          },
          "properties": {
            "scheme": {
              "not": {
                "enum": [
                  "bearer"
                ]
              }
            }
          }
        }
      ]
    },
    "Schema_ImplicitOAuthFlow": {
      "type": "object",
      "required": [
        "authorizationUrl",
        "scopes"
      ],
      "properties": {
        "authorizationUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "refreshUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "scopes": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_OAuth2SecurityScheme": {
      "type": "object",
      "required": [
        "type",
        "flows"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "oauth2"
          ]
        },
        "flows": {
          "$ref": "#/definitions/Schema_OAuthFlows"
        },
        "description": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_OAuthFlows": {
      "type": "object",
      "properties": {
        "implicit": {
          "$ref": "#/definitions/Schema_ImplicitOAuthFlow"
        },
        "password": {
          "$ref": "#/definitions/Schema_PasswordOAuthFlow"
        },
        "clientCredentials": {
          "$ref": "#/definitions/Schema_ClientCredentialsFlow"
        },
        "authorizationCode": {
          "$ref": "#/definitions/Schema_AuthorizationCodeOAuthFlow"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_OpenIdConnectSecurityScheme": {
      "type": "object",
      "required": [
        "type",
        "openIdConnectUrl"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "openIdConnect"
          ]
        },
        "openIdConnectUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "description": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_PasswordOAuthFlow": {
      "type": "object",
      "required": [
        "tokenUrl"
      ],
      "properties": {
        "tokenUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "refreshUrl": {
          "type": "string",
          "format": "uri-reference"
        },
        "scopes": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "patternProperties": {
        "^x-": {}
      },
      "additionalProperties": false
    },
    "Schema_Reference": {
      "type": "object",
      "required": [
        "$ref"
      ],
      "patternProperties": {
        "^\\$ref$": {
          "type": "string",
          "format": "uri-reference"
        }
      }
    },
    "Schema_SecurityScheme": {
      "oneOf": [
        {
          "$ref": "#/definitions/Schema_APIKeySecurityScheme"
        },
        {
          "$ref": "#/definitions/Schema_HTTPSecurityScheme"
        },
        {
          "$ref": "#/definitions/Schema_OAuth2SecurityScheme"
        },
        {
          "$ref": "#/definitions/Schema_OpenIdConnectSecurityScheme"
        }
      ]
    }
  }
}

=== wmo-im/wis2-notification-message/examples/eumetsat-msg-seviri-recommended-api-notification.json
{
    "id": "20043c6a-5ceb-4601-8f77-1a7c71968d53",
    "version": "v04",
    "type": "Feature",
    "geometry": null,
    "properties": {
        "data_id": "wis2/int-eumetsat/data/core/weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5/EO:EUM:DAT:MSG:HRSEVIRI-MSG3-SEVI-MSG15-0100-NA-20240122075742.471000000Z-NA",
        "metadata_id": "urn:wmo:md:int:eumetsat:EO:EUM:DAT:MSG:HRSEVIRI3",
        "pubtime": "2024-01-18T12:05:02Z",
        "integrity": {
            "method": "sha512",
            "value": "5a4cae86ee22d91f349ac51e24db08eba33f42950bdb295a78fdd00532bffc924bffa9e40b7d246e0b3629d4d7b2398e54710179e611d42aa9ef86ec0f2599e5"
        },
        "datetime": "2024-01-22T07:45:00Z"
    },
    "links": [
        {
            "rel": "service",
            "href": "https://https://apieumetsat.int/data/download/",
            "type": "application/octet-stream",
            "title": "Datastore Download API"
        },
        {
            "href": "https://eumetsatspace.atlassian.net/wiki/spaces/DSDS/pages/1903919105/Swagger+UI+Download+REST+API+1.0.0",
            "rel": "canonical",
            "type": "text/html"
        }
    ]
}

=== wmo-im/wis2-notification-message/examples/example4.json
{
    "id": "31e9d66a-cd83-4174-9429-b932f1abcdef",
    "version": "v04",
    "type": "Feature",
    "geometry": null,
    "properties": {
        "pubtime": "2022-12-22T16:40:37Z",
        "datetime": "2022-11-11T11:11:11Z",
        "data_id": "data/data-123/items/abcdefab-abcd-1234-5678-0123456789ab",
        "metadata_id": "urn:x-wmo:md:xyz:nmhs_xyz:some_dataset",
        "cache": false
    },
    "links": [
        {
            "href": "https://example.org/92c557ef-d28e-4713-91af-2e2e7be6f8ab.txt",
            "rel": "http://def.wmo.int/def/rel/wnm/-/deletion"
        }
    ]
}

=== wmo-im/wis2-notification-message/examples/eumetsat-msg-seviri-recommended-notification.json
{ 
  "id": "e545ffcf-bacf-7713-9f942-beb321", 
  "version": "v04", 
  "type": "Feature", 
  "geometry": null, 
  "properties": { 
    "data_id": "wis2/int-eumetsat/data/core/weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5/EO:EUM:DAT:MSG:HRSEVIRI-MSG3-SEVI-MSG15-0100-NA-20240122075742.471000000Z-NA", 
    "metadata_id": "urn:x-wmo:md:int:eumetsat:EO:EUM:DAT:MSG:HRSEVIRI3", 
    "pubtime": "2024-01-18T12:05:02Z", 
    "integrity": { 
      "method": "sha512", 
      "value": "5a4cae86ee22d91f349ac51e24db08eba33f42950bdb295a78fdd00532bffc924bffa9e40b7d246e0b3629d4d7b2398e54710179e611d42aa9ef86ec0f2599e5" 
    }, 
    "datetime": "2024-01-22T07:45:00Z" 
  }, 
  "links": [ 
    { 
      "href": "https://api.eumetsat.int/data/download/1.0.0/collections/EO%3AEUM%3ADAT%3A0410/products/S3A_OL_1_ERR____20240121T151343_20240121T155733_20240121T171621_2630_108_125______MAR_O_NR_002.SEN3", 
      "rel": "canonical", 
      "type": "application/zip", 
      "length": 4023452 
    },
    {
      "href": "https://user.eumetsat.int/resources/user-guides/data-store-detailed-guide",
      "rel": "about",
      "type": "text/html"
    }
  ] 
}

=== wmo-im/wis2-notification-message/examples/eumetsat-msg-seviri-core-notification.json
{
    "id": "e686f5cf-bacf-4703-9f94-217e2b5d5ebb",
    "conformsTo": [
        "http://wis.wmo.int/spec/wnm/1/conf/core"
    ],
    "type": "Feature",
    "geometry": null,
    "properties": {
        "data_id": "wis2/int-eumetsat/data/core/weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5/H-000-MSG3__-MSG3________-IR_134___-000001___-202401181200-C_",
        "metadata_id": "urn:wmo:md:int:eumetsat:EO:EUM:DAT:MSG:HRSEVIRI3",
        "pubtime": "2024-01-18T12:05:02Z",
        "integrity": {
            "method": "sha512",
            "value": "5a4cae86ee22d91f349ac51e24db08eba33f42950bdb295a78fdd00532bffc924bffa9e40b7d246e0b3629d4d7b2398e54710179e611d42aa9ef86ec0f2599e5"
        },
        "datetime": "2024-01-18T12:00:00Z"
    },
    "links": [
        {
            "href": "https://wisdev.kishou.go.jp/data/wis2/int-eumetsat/data/core/weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5/H-000-MSG3__-MSG3________-IR_134___-000001___-202401181200-C_/H-000-MSG3__-MSG3________-IR_134___-000001___-202401181200-C_",
            "rel": "canonical",
            "type": "application/octet-stream",
            "length": 409575
        }
    ]
}

=== wmo-im/wis2-notification-message/examples/example2.json
{
    "id": "31e9d66a-cd83-4174-9429-b932f1abe1be",
    "conformsTo": [
        "http://wis.wmo.int/spec/wnm/1/conf/core"
    ],
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -7.75,
                    40.43
                ],
                [
                    -7.75,
                    78.46
                ],
                [
                    71.91,
                    78.46
                ],
                [
                    71.91,
                    40.43
                ],
                [
                    -7.75,
                    40.43
                ]
            ]
        ]
    },
    "properties": {
        "pubtime": "2022-03-20T04:50:18Z",
        "start_datetime": "2022-03-20T00:06:00Z",
        "end_datetime": "2022-03-20T00:12:00Z",
        "integrity": {
            "method": "sha512",
            "value": "A2KNxvks...S8qfSCw=="
        },
        "data_id": "dataset/4546/abcdef-abcd-abcd-abcd-abcdefabcd",
        "metadata_id": "urn:wmo:md:fr-meteo-france:gap123"
    },
    "links": [
        {
            "href": "https://example.org/data/nwp/92c557ef-d28e-4713-91af-2e2e7be6f8ab.grib",
            "rel": "canonical",
            "type": "application/x-grib2"
        }
    ]
}
